package cl.fonasa.soa.mensajes.cuentamedicainteroperable;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2018-03-09T12:42:07.228-04:00
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "FONASAcuentaMedicaInteroperableSEC", 
                  wsdlLocation = "file:/C:/Eclipse/eclipse-jee-mars-2-wso2-ei/workspace/wsdl2java/src/main/resources/FONASAcuentaMedicaInteroperable.wsdl",
                  targetNamespace = "http://soa.fonasa.cl/mensajes/cuentaMedicaInteroperable") 
public class FONASAcuentaMedicaInteroperableSEC extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soa.fonasa.cl/mensajes/cuentaMedicaInteroperable", "FONASAcuentaMedicaInteroperableSEC");
    public final static QName CuentaMedicaInteroperableBindQSPort = new QName("http://soa.fonasa.cl/mensajes/cuentaMedicaInteroperable", "cuentaMedicaInteroperable_bindQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Eclipse/eclipse-jee-mars-2-wso2-ei/workspace/wsdl2java/src/main/resources/FONASAcuentaMedicaInteroperable.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FONASAcuentaMedicaInteroperableSEC.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Eclipse/eclipse-jee-mars-2-wso2-ei/workspace/wsdl2java/src/main/resources/FONASAcuentaMedicaInteroperable.wsdl");
        }        
        WSDL_LOCATION = url;
    }

    public FONASAcuentaMedicaInteroperableSEC(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FONASAcuentaMedicaInteroperableSEC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FONASAcuentaMedicaInteroperableSEC() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FONASAcuentaMedicaInteroperableSEC(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FONASAcuentaMedicaInteroperableSEC(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FONASAcuentaMedicaInteroperableSEC(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CuentaMedicaInteroperablePtt
     */
    @WebEndpoint(name = "cuentaMedicaInteroperable_bindQSPort")
    public CuentaMedicaInteroperablePtt getCuentaMedicaInteroperableBindQSPort() {
        return super.getPort(CuentaMedicaInteroperableBindQSPort, CuentaMedicaInteroperablePtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentaMedicaInteroperablePtt
     */
    @WebEndpoint(name = "cuentaMedicaInteroperable_bindQSPort")
    public CuentaMedicaInteroperablePtt getCuentaMedicaInteroperableBindQSPort(WebServiceFeature... features) {
        return super.getPort(CuentaMedicaInteroperableBindQSPort, CuentaMedicaInteroperablePtt.class, features);
    }

}
